# please use the enviroment variable or don't change the env names update based on that!!!!

spring:
  application:
    name: ticketing-service
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${TI_CORE_DB_URL:jdbc:postgresql://localhost:5433/tele-insight-ticketing-db}
    username: ${TI_CORE_DB_USERNAME:postgres}
    password: ${TI_CORE_DB_PASSWORD:root}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:0}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

springdoc:
  swagger-ui:
    path: /docs/ticketing/swagger-ui.html
  api-docs:
    path: /docs/ticketing/api-docs
