# please use the enviroment variable or don't change the env names update based on that!!
spring:
  application:
    name: service-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: ${GATEWAY_DISCOVERY_SERVER_URI:http://localhost:8761}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: ${GATEWAY_DISCOVERY_SERVER_URI:http://localhost:8761}
          predicates:
            - Path=/eureka/**

        - id: ticketing-service
          uri: lb://ticketing-service
          predicates:
            - Path=/api/v1/ticketing/**, /docs/ticketing/**
          filters:
            - AuthenticationFilter

        - id: insight-service
          uri: lb://insight-service
          predicates:
            - Path=/api/v1/blog/**, /docs/insight/**
          filters:
            - AuthenticationFilter

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**, /docs/auth/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

server:
  port: ${SERVER_PORT:8080}
